name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  TestingUtama:
    name: cpp test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Konfigurasi statik lint cpp
        run: cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    
  build:
    name: cek compile
    runs-on: ${{ matrix.os }}
    needs: [TestingUtama]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - run: cmake -B ./build -S .
    - run: cmake --build build
      
